config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get '/login',   to: 'registrations#new'
    post '/login',   to: 'registrations#create'
    delete '/logout',  to: 'registrations#destroy'

resources :users do
  resources :gossips do
    resources :comments do
      resources :commentofcomments
    end
    resources :likes
  end
end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :gossip
    belongs_to :user
    has_many :commentofcomments
end

app/models/commentofcomment.rb
class Commentofcomment < ApplicationRecord
    belongs_to :comment
    belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    #has_and_belongs_to_many :tags
    has_many :comments, dependent: :destroy
    has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/user.rb
class User < ApplicationRecord
    has_many :gossips
    has_many :likes
    has_many :comments
    has_many :commentofcomments
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     include RegistrationsHelper
end

app/controllers/commentofcomments_controller.rb
class CommentofcommentsController < ApplicationController
    def new
        @user=User.find(current_user.id)

    end

    def create
        @gossip = Gossip.find(params[:gossip_id])
        @comment = Comment.find(params[:comment_id])
        @commentofcomment=Commentofcomment.create!(user_id: current_user.id, comment_id: @comment.id, content: params[:commentofcomment][:content])
        puts @commentofcomment
        redirect_to "/users/#{current_user.id}/gossips/#{@gossip.id}"
    end

    def destroy
        @gossip = Gossip.find(params[:gossip_id])
        @comment = Comment.find(params[:comment_id])
        @commentofcomment = @comment.commentofcomments.find(params[:id])
        @commentofcomment.destroy
        redirect_to "/users/#{current_user.id}/gossips/#{@gossip.id}"
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        @user=User.find(current_user.id)
    end

    def create
        @gossip = Gossip.find(params[:gossip_id])
        @comment=Comment.create!(user_id: current_user.id, gossip_id: @gossip.id, content: params[:comment][:content])
        puts @comment
        redirect_to "/users/#{current_user.id}/gossips/#{@gossip.id}"
    end

    def destroy
        @gossip = Gossip.find(params[:gossip_id])
        @comment = @gossip.comments.find(params[:id])
        @comment.destroy
        redirect_to "/users/#{current_user.id}/gossips/#{@gossip.id}"
    end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
  @gossips=Gossip.all
  @user= User.find(params[:user_id])
  end

  def show
    @gossip=Gossip.find(params[:id])
    @user= User.find(params[:user_id]) 
    @comment = Comment.new
    @comments = @gossip.comments
    if Like.find_by(user_id: current_user.id, gossip_id: @gossip.id) == nil
      @like = Like.new
      @verif= true
    else
      @verif = false
      @like = Like.find_by(user_id: current_user.id, gossip_id: @gossip.id)
    end
  end

  def update
    @gossip=Gossip.find(params[:id])
    @gossip.update(gossip_params)
    redirect_to "/users/#{current_user.id}/gossips/"
  end

  def destroy
    @gossip=Gossip.find(params[:id])
    @user = @gossip.user
    @gossip.destroy
    redirect_to "/users/#{current_user.id}/gossips/"
  end

  def new
    @gossip = Gossip.new
  end

  def edit
    @gossip=Gossip.find(params[:id])
  end

  def create
    @gossip = Gossip.create(user_id: current_user.id, content: params[:gossip][:content], title: params[:gossip][:title])
    redirect_to "/users/#{current_user.id}/gossips/"
  end

  private
  def gossip_params
    params.require(:gossip).permit(:title, :content)
    end

end

app/controllers/likes_controller.rb
    class LikesController < ApplicationController

    def new
        @user=User.find(current_user.id)
    end

    def create
        @gossip = Gossip.find(params[:gossip_id])
        @like=Like.create!(user_id: current_user.id, gossip_id: @gossip.id)
        redirect_to "/users/#{current_user.id}/gossips/#{@gossip.id}"
    end

    def destroy
        @gossip = Gossip.find(params[:gossip_id])
        puts "Ta maman #{@gossip}"
        @like = @gossip.likes.find(params[:id])
        puts "Ta maman #{@like}"
        @like.destroy
        redirect_to "/users/#{current_user.id}/gossips/#{@gossip.id}"
    end
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
  end




  def create
    userlog=User.find_by(email: params[:registration][:email].downcase)
    if params[:registration][:password] == userlog.password
      login userlog
      redirect_to userlog
      #redirect_to "/users/#{userlog.id}"
    #if user && user.authenticate(params[:registration][:password])

      #redirect_to user
      #Va log l'utilisateur et le rediriger vers la page de l'utilisateur
    else
      #va créer un message d'erreur
    flash.now[:danger] = 'Email ou password invalide'
    render 'new'

    end
  end

  def destroy
    log_out
    redirect_to ''
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
def home
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user=User.new
  end

   def create    
    @user = User.create(user_params)
    login @user
    flash.now[:success] = "C'est good !"
    redirect_to user_path(@user.id)
  end

  def show
    @user=User.find(params[:id])
    puts params
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commentofcomments_helper.rb
module CommentofcommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
    def login(user)
        session[:user_id] = user.id
    end
    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/commentofcomments/_commentofcomment.html.erb
<class="commofcomm" style="margin-left: 50px">
    <pre style="color: green; font-weight: bold"><%= User.find(commentofcomment.user_id).name %> : </pre><cite><%= commentofcomment.content %></cite>
    <pre style="font-size: 90%">          - <%= time_ago_in_words(commentofcomment.created_at) %></pre>
    <% if commentofcomment.user_id == current_user.id %>
        <%= link_to 'Delete',[commentofcomment.comment.gossip.user, commentofcomment.comment.gossip, commentofcomment.comment, commentofcomment], method: :delete, data: { confirm: "T'es sûr de sûr ?"} %>
    <% end %>
</class>

app/views/commentofcomments/_form.html.erb
<%= form_for ([@user, @gossip, @comm, @comm.commentofcomments.build]), method: :post do |f| %>
<div class="form-inline">    
        <%= f.text_area :content, rows: "1", placeholder: 'Ton vilain comm de comm', class: "form-control form-control-sm" %>    
        <button style="margin: 20px;", class="btn btn-outline-dark btn-sm mb-2" type="submit">Commenter</button>    
</div>
<% end %>

app/views/comments/_comment.html.erb
<div class="com" style="margin-left: 20px !important;"">
    <pre style="color: blue; font-weight: bold; font-size: 140%"><%= User.find(comment.user_id).name %> : </pre><cite><%= comment.content %></cite>
<pre style="font-size: 140%">          - <%= time_ago_in_words(comment.created_at) %></pre>
<p>
    <% if comment.user_id == current_user.id %>
    <%= link_to 'Delete',[comment.gossip.user, comment.gossip, comment], method: :delete, data: { confirm: "T'es sûr de sûr ?"} %>
    <% end %>
</p>
<%= render comment.commentofcomments %>
<%@comm = @comments[@c] %>
<%= render 'commentofcomments/form' %>
<%@c+=1%>

</div>

app/views/comments/_form.html.erb
<%= form_for ([@user, @gossip, @gossip.comments.build]), method: :post do |f| %>
<div class="form-group">
    <%= f.text_area :content, placeholder: 'Ton vilain commentaire', class: "form-control" %>
</div>
<div class="form-group">
    <button class="btn btn-outline-dark" type="submit">Commenter</button>
</div>
<% end %>

app/views/gossips/create.html.erb
<h1>Gossips#create</h1>
<p>Find me in app/views/gossips/create.html.erb</p>

app/views/gossips/destroy.html.erb
<h1>Gossips#destroy</h1>
<p>Find me in app/views/gossips/destroy.html.erb</p>

app/views/gossips/edit.html.erb
<body>
<h1>Édite ton nouveau gossip ! <img src="http://image.noelshack.com/fichiers/2018/44/4/1541101054-wineload.gif" height="60" width="60"></h1>

<%= form_for @gossip, url: {action: "update"} do |f| %>
<div class="form-group">
    <%= f.text_field :title, placeholder: 'Ton joli petit titre', class: "form-control" %>
</div>
<div class="form-group">
    <%= f.text_area :content, placeholder: 'Ton vilain gossip', class: "form-control" %>
</div>
<div class="form-group">
    <button class="btn btn-outline-dark" type="submit">Modifier le gossip</button>
</div>
<% end %>

app/views/gossips/index.html.erb
<body style="padding-left:10px;padding-right:10px;">
<h1>Nos gossips ! <img src="http://image.noelshack.com/fichiers/2018/44/4/1541101054-wineload.gif" height="60" width="60"></h1>

<table class="table">
    <thead>
        <tr>
            <td>ID</td>
            <td>Gossiper</td>
            <td>Titre</td>            
            <td>Content</td>
            <td>Nombre de commentaires</td>
            <td>Nombre de likes</td>
        </tr>
    </thead>
    <tbody>
    <% @gossips.each do |gossip| %>
    <tr>
        <td><%= gossip.id %></td>
        <td><%= gossip.user.name %></td>
        <td><%= gossip.title %></td>
        <td><%= gossip.content %></td>
        <td><%= gossip.comments.count %></td>
        <td><%= gossip.likes.count %></td>
        <td>
            <a href="/users/<%=current_user.id%>/gossips/<%=gossip.id%>" class="btn btn-outline-dark">Voir le potin</a>
            <% if current_user.id == gossip.user_id %>
            <a href="/users/<%=current_user.id%>/gossips/<%=gossip.id%>/edit" class="btn btn-warning">Éditer</a>
            <a href="<%=user_gossip_path(current_user.id, gossip.id)%>" class="btn btn-danger" data-method="DELETE">Supprimer</a>
            <%end%>
        </td>

    </tr>
    <% end %>
    </tbody>
</table>

<p>
    <a href="/users/<%=current_user.id%>/gossips/new" class="btn btn-success">Créer ton nouveau gossip !</a>
</p>
</body>

app/views/gossips/new.html.erb
<h1>Ton nouveau gossip ! <img src="http://image.noelshack.com/fichiers/2018/44/4/1541101054-wineload.gif" height="60" width="60"></h1>

<%= form_for @gossip, url: {action: "create"} do |f| %>
<div class="form-group">
    <%= f.text_field :title, placeholder: 'Ton joli petit titre', class: "form-control" %>
</div>
<div class="form-group">
<%= f.text_area :content, placeholder: 'Ton vilain gossip', class: "form-control" %>
</div>
<div class="form-group">
    <button class ="btn btn-outline-dark" type="submit">Créer le gossip</button>
</div>
<% end %>

app/views/gossips/show.html.erb
<body style="margin-left: 10px">
<!-- #NOM UTILISATEUR -->
<h1>Voilà le potin de ses morts de <%=@gossip.user.name%>! <img src="http://image.noelshack.com/fichiers/2018/44/4/1541101054-wineload.gif" height="60" width="60"></h1>
<br><br>
<h1>Titre de merde : <%=@gossip.title%></h1>
<br><br>
<!-- #GOSSIP CONTENT -->
<h2><blockquote>
        <img src="http://image.noelshack.com/fichiers/2018/44/4/1541076385-silent-clipart-whispers-10.png" 
        height="30" width="30">
        <%= @gossip.content %>
</blockquote></h2>
<!-- #BOUTON LIKE -->
<%= render 'likes/like' %> 
<br>
<!-- #COMPTEUR LIKE -->
<p><%= @gossip.likes.count %> likes </p>
<!-- #COMPTEUR COMMENTAIRE -->
<p><%= @gossip.comments.count %> commentaires </p>
<%@c=0%>
<%= render @gossip.comments %>
<h3>Ajouter un commentaire:</h3>
<!-- #AJOUT COMMENTAIRE -->
<%= render 'comments/form' %>

<p><a href="/users/<%=current_user.id%>/gossips" class="btn btn-primary">Revenir aux gossips</a></p>
</body>

app/views/gossips/update.html.erb
<h1>Gossips#update</h1>
<p>Find me in app/views/gossips/update.html.erb</p>

app/views/likes/_like.html.erb
<p> 
    <% if @verif == true %>
     <%= link_to image_tag("http://image.noelshack.com/fichiers/2018/44/4/1541109258-likeempty.png"), user_gossip_likes_path(@user, @gossip), method: :post, remote: true %> CLIQUE POUR LIKE !
    <% else %>
    <%= link_to image_tag("http://image.noelshack.com/fichiers/2018/44/4/1541109258-likefull.png"), [@like.gossip.user, @like.gossip, @like], method: :delete %> CLIQUE POUR UNLIKE !
    <% end %>
</p>

app/views/static_pages/home.html.erb
<div class="accueil">

    <div class="logo_accueil">
        <img src="http://image.noelshack.com/fichiers/2018/44/4/1541075275-dvir.gif" height="240" width="240">
        <img src="http://image.noelshack.com/fichiers/2018/44/4/1541075037-thpbdx1gossip.png">
        <img style="-moz-transform: scaleX(-1); -o-transform: scaleX(-1); -webkit-transform: scaleX(-1); transform: scaleX(-1); filter: FlipH; -ms-filter: "FlipH" " src="http://image.noelshack.com/fichiers/2018/44/4/1541075275-dvir.gif" height="240" width="240">
    </div>
     <div class="button_inscription">    
            <%= link_to "inscription", new_user_path, class: "btn btn-primary btn-lg" %>
     </div>
    <div class="button_login">   
            <a class="btn btn-primary btn-lg" href="login" role="button">connecte toi</a>
    </div>

</div>

app/views/users/new.html.erb
<h1 style="margin: 25px;"><a href="https://www.youtube.com/watch?v=uG5Phc6GxKY">Alors infidèle</a>, on est pas encore enregistré ? <img src="http://image.noelshack.com/fichiers/2018/44/4/1541101054-wineload.gif" height="60" width="60"></h1>
<br>
<%= form_for @user do |f| %>
<div class="form-group row">
<div class="col-sm-50" style="margin: 25px;">
    <%= f.text_field :name, placeholder: 'Pseudo', class: "form-control" %>
</div>
<div class="col-sm-100" style="margin: 25px;">
    <%= f.text_field :email, placeholder: 'Email', class: "form-control" %>
</div>
<div class="col-sm-75" style="margin: 25px;">
    <%= f.text_field :password, placeholder: 'Mot de passe', class: "form-control" %>
</div>
<div class="col-sm-30" style="margin: 25px;">
    <button class="btn btn-outline-dark" type="submit">Créer ton utilisateur</button>
</div>
</div>

<% end %>

app/views/users/show.html.erb
<div id="usershow">
<h1>Bienvenue <%= @user.name %> <img src="http://image.noelshack.com/fichiers/2018/44/4/1541101054-wineload.gif" height="60" width="60"></h1>
<div class="button_login">   
    <a class="btn btn-primary btn-lg" href="/users/<%=@user.id%>/gossips/" role="button">GOSSIPS</a>
    <%= link_to "Reviens à l'accueil", '/', class: "btn btn-lg btn-primary" %>
</div>
</div>